eval_data:
  file_name: ./inputs/packative_nl2sql_eval_20241029(final-edited).csv
  out_folder: ./outputs
  plot_folder: ./plots
  results_tag: en
  results_file_name: ./outputs/packative_nl2sql_eval_20241029(final-edited)(en).json
  # results_file_name: ./outputs/packative_nl2sql_eval_20241029(final-edited)(ko).json
  in:
    nlq_col: nl_en_query
    # nlq_col: nl_ko_query
    user_id_col: user_id
    ex_label_col: execution_result_sqlalchemy
    sql_col: sql_query
    template_id_col: no_sql_template
  out:
    pred_ex_label_col: pred_execution_result
    pred_sql_col: pred_sql_query
    pred_template_id_col: pred_template_id

inference:
  client: test
  dataset: custom
  db_type: postgres
  db_name: packative
  collection: PackativeMultilingualv3ClusteringRedux
  # url: http://localhost:8000/api/predictions
  url: https://betterdemo.gena.co/nl2sqlapi/predictions
  gen_models:
    - backend: azure
      model: gena-4o
    # - backend: bedrock
    #   model: meta.llama3-1-8b-instruct-v1:0
    # - backend: bedrock
    #   model: mistral.mistral-7b-instruct-v0:2
    
    # - mistral.mistral-large-2402-v1:0
    # - mistral.mistral-large-2407-v1:0
    # - mistral.mixtral-8x7b-instruct-v0:1
    # - us.meta.llama3-2-1b-instruct-v1:0
    # - us.meta.llama3-2-3b-instruct-v1:0
  gen_mods:
    - fillin
    - fewshot
    - template
  num_of_workers: 8

metrics:
  - name: execution_match
    output_column: ex_match
    plot_label: Execution Match Accuracy
  - name: sql_match
    output_column: sql_match
    plot_label: SQL Match Accuracy
  - name: intent_match
    output_column: intent_match
    plot_label: Intent Match Accuracy
  - name: soft_f1_score
    output_column: soft_f1_score
    plot_label: Soft F1 Score
  - name: template_match
    output_column: template_match
    plot_label: Template Match Accuracy