REFUND_REASONS = [
    "Wrong order received",
    "Food quality issues",
    "Excessive delivery delay",
    "Missing items",
    "Temperature issues",
]
POSITIVE_COMMENTS_FOOD = [
    "Great food and fast delivery!",
    "Excellent service, will order again",
    "Food was fresh and delicious",
    "Perfect portion sizes and good value",
    "Amazing flavors, exceeded expectations!",
    "Driver was very professional and friendly",
    "Food arrived piping hot and well-packaged",
    "Best takeout I've had in months",
    "Super responsive customer service",
    "Restaurant included extra condiments - nice touch",
    "Delivery was earlier than estimated",
    "Quality ingredients, you can really taste the difference",
    "Packaging kept everything separate and fresh",
    "Menu prices are very reasonable",
    "Love the authentic taste",
    "Everything was exactly as ordered",
    "Great attention to dietary restrictions",
    "Would highly recommend to friends",
    "Consistently good quality every time",
    "Restaurant followed all special instructions",
    "Generous portions for the price",
    "Food presentation was beautiful",
    "Five stars for taste and service",
    "Perfect temperature on arrival",
]
NEGATIVE_COMMENTS_FOOD = [
    "Food was cold on arrival",
    "Long waiting time",
    "Portion sizes were small",
    "Not worth the price",
    "Order was missing items",
    "Wrong items delivered",
    "Food quality has declined",
    "Driver couldn't find the address",
    "No utensils included as requested",
    "Delivery fee was too high",
    "Food wasn't packaged properly",
    "Items were damaged during delivery",
    "Taste didn't match the description",
    "Restaurant ignored special instructions",
    "Website prices don't match delivery app",
    "Food wasn't fresh",
    "Customer service was unhelpful",
    "Order took twice the estimated time",
    "Items were mixed up in packaging",
    "Delivery person was rude",
    "Food didn't taste like advertised",
    "Quality doesn't justify cost",
    "Had to call multiple times for updates",
    "Wouldn't recommend to others",
]
POSITIVE_COMMENTS_DELIVERY = [
    "Delivery was quick and professional",
    "Driver was very courteous",
    "Perfect delivery experience",
    "Food arrived hot and well-packaged",
    "Driver went above and beyond",
    "Excellent communication throughout delivery",
    "Delivery person followed all instructions perfectly",
    "Food was handled with care",
    "Delivered right to my door",
    "Driver was friendly and efficient",
    "Order arrived earlier than expected",
    "Very smooth delivery process",
    "Driver maintained great professionalism",
    "Delivery tracking was accurate",
    "Food packaging was secure and intact",
    "Driver wore appropriate PPE",
    "Contactless delivery was executed perfectly",
    "Driver found location without any issues",
    "Great attention to special delivery instructions",
    "Delivery person was patient and understanding",
    "Everything arrived in perfect condition",
    "Driver communicated estimated arrival time",
    "Excellent service from start to finish",
    "Very satisfied with the delivery service",
]
NEGATIVE_COMMENTS_DELIVERY = [
    "Delivery took longer than expected",
    "Driver was not following directions",
    "Poor communication",
    "Food arrived cold",
    "Wrong address delivery attempt",
    "Driver was unprofessional",
    "No updates on delivery status",
    "Items were damaged during delivery",
    "Driver couldn't find location",
    "Delivery person ignored instructions",
    "Multiple delivery attempts needed",
    "Food packaging was damaged",
    "Driver didn't use hot bag",
    "No notification of arrival",
    "Delivery person was rude",
    "Order was incomplete upon delivery",
    "Driver left food in wrong location",
    "Poor handling of fragile items",
    "Delivery time estimate was inaccurate",
    "No response to customer messages",
    "Items were missing upon delivery",
    "Driver refused to follow delivery notes",
    "Very long wait time",
    "Delivery person seemed lost",
]
PAYMENT_METHODS = ["Credit Card", "Debit Card", "PayPal", "Cash on Delivery"]

FEEDBACK_OPTIONS = [
    # Original feedback
    "Great app! Very intuitive and easy to use.",
    "The delivery tracking feature is amazing!",
    "Would love to see more filter options for restaurants.",
    "App crashes sometimes when loading images.",
    "Payment process could be more streamlined.",
    "Please add more payment methods.",
    "Love the new loyalty program feature!",
    "Menu items should show allergen information.",
    # User Interface & Experience
    "Dark mode would be a great addition to the app.",
    "The search function needs improvement - results aren't always relevant.",
    "Could you make the font size adjustable?",
    "Love how fast the app loads compared to competitors!",
    "The new UI update is fantastic - much cleaner look.",
    "Sometimes the back button behaves unexpectedly.",
    "The map interface is really smooth and responsive.",
    "Would appreciate more customization options for the home screen.",
    # Orders & Delivery
    "Estimated delivery times are very accurate.",
    "Need an option to modify orders after placing them.",
    "Great feature being able to split bills with friends!",
    "Could use more detailed order status updates.",
    "The real-time driver tracking is inconsistent sometimes.",
    "Love being able to schedule orders in advance.",
    "Would be nice to have a reorder button for frequent orders.",
    "Please add an option to save delivery instructions permanently.",
    # Restaurant & Menu
    "Photos of menu items are really helpful.",
    "Need more vegan and vegetarian filtering options.",
    "Would love to see calories listed for menu items.",
    "Restaurant ratings could use more detailed categories.",
    "The menu search feature is fantastic!",
    "Please add more sorting options for restaurant listings.",
    "Could use better descriptions for spice levels.",
    "Love the new feature showing peak busy hours!",
    # Payment & Pricing
    "The price comparison feature is super helpful.",
    "Sometimes promotional codes don't apply correctly.",
    "Would love an option to save multiple cards securely.",
    "Great how tax and fees are clearly broken down.",
    "The tipping interface could be more intuitive.",
    "Auto-calculate group payment splits would be nice.",
    "Need clearer refund status tracking.",
    "Love the instant payment confirmation notifications!",
    # Account & Support
    "Customer service chat response times are great.",
    "Would appreciate more detailed order history.",
    "The help section could use better organization.",
    "Love how easy it is to update account information.",
    "Need more options for notification preferences.",
    "Great feature being able to share favorite restaurants.",
    "Could use better integration with social media.",
    "Password reset process is unnecessarily complicated.",
    # Special Features
    "The local restaurant recommendations are spot-on!",
    "Would love to see a points sharing system with family.",
    "The holiday special offers section is well organized.",
    "Need better filters for dietary restrictions.",
    "Love the new food photo sharing community feature!",
]
NOTIFICATIONS = [
    "Your order #{} has been delivered!",
    "Rate your recent experience with us!",
    "Special offer: Get 20% off on your next order!",
    "New restaurant has joined in your area!",
]
