log_folder: ./logs
outputs_folder : ./outputs_100_sc
results_folder: ./results_100_sc
plots_folder: ./plots_100_sc
inference_folder: ./inference_100_sc
database_type: postgres
train_file_path: ./data/packative_nl2sql_train_en_20241114.csv
train_embedding_file_path: ./data/packative_nl2sql_train_en_20241114_embedding.npy
test_file_path: ./data/packative_nl2sql_eval_fixed20241119_20241128.csv
collection_name: packative_collection_1
batch_size: null
max_workers: 4

question_key: question
target_sql_key: SQL

pipe_configurations:
  - formatter: GENACoT
    rewrite: True
    repair: True
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: gcp-gemini
      model: gemini-1.5-flash-8b
      config:
        temperature: 0
      top_k: 3
    candidate_count: 1
    pipe_name: pipe_v1
  - formatter: GENACoTZs
    repair: True
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: gcp-gemini
      model: gemini-2.0-flash-exp
      config:
        temperature: 0.5
      top_k: 5
    candidate_count: 5
    pipe_name: pipe_v2
  - formatter: legacy
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: azure-gpt
      model: gena-4o-2024-08-06
      config:
        temperature: 1
      top_k: 8
    candidate_count: 3
    pipe_name: pipe_v3
