log_folder: ./logs
outputs_folder : ./outputs_100_sc
results_folder: ./results_100_sc
plots_folder: ./plots_100_sc
inference_folder: ./inference_100_sc
train_file_path: ./data/packative_synthesized_data_20241108.csv
train_embedding_file_path: ./data/packative_synthesized_data_20241108_nl_query_keymap_packative_synth_embeddings.npy
test_file_path: ./data/packative_nl2sql_eval_fixed20241119_20241128_cleans.csv
batch_size: null
max_workers: 4

pipe_configurations:
  - formatter: GENACoT
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: gcp-gemini
      model: gemini-1.5-flash-8b
      config:
        temperature: 0
      top_k: 3
    candidate_count: 1
    pipe_name: pipe_v1
  - formatter: GENACoT
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: gcp-gemini
      model: gemini-2.0-flash-exp
      config:
        temperature: 0.5
      top_k: 5
    candidate_count: 5
    pipe_name: pipe_v2
  - formatter: GENACoT
    schema: basic
    postfunc: extract_first_code_block
    generator:
      name: azure-gpt
      model: gena-4o-2024-08-06
      config:
        temperature: 1
      top_k: 8
    candidate_count: 3
    pipe_name: pipe_v3
