top_k: 3

configs:
  - generator: azure
    model: gpt-4o-bird
    schema_filtering: column
    schema_format: sql_create
  - generator: azure
    model: gpt-4o-bird
    schema_filtering: column
    schema_format: m_schema
  - generator: azure
    model: gpt-4o-bird
    schema_filtering: table
    schema_format: m_schema
  - generator: gcp
    model: gemini-1.5-pro
    schema_filtering: none
    schema_format: mac_schema
  - generator: gcp
    model: gemini-1.5-pro
    schema_filtering: column
    schema_format: mac_schema
