top_k: 3

configs:
  - schema_format: sql_create
    schema_filtering: column
    generator: azure
    model: gpt-4o-bird
  - schema_format: m_schema
    schema_filtering: column
    generator: azure
    model: gpt-4o-bird
  - schema_format: m_schema
    schema_filtering: table
    generator: azure
    model: gpt-4o-bird
  - schema_format: mac_schema
    schema_filtering: none
    generator: gcp
    model: gemini-1.5-pro
  - schema_format: mac_schema
    schema_filtering: column
    generator: gcp
    model: gemini-1.5-pro
